apiVersion: v1
kind: Service
metadata:
  name: opencloudcxapp-svc
  labels:
    app: opencloudcxapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: opencloudcxapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencloudcxapp
  labels:
    app: opencloudcxapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opencloudcxapp
  template:
    metadata:
      labels:
        app: opencloudcxapp
    spec:
      containers:
      - name: opencloudcxapp
        image: gboie/opencloudcxapp:latest
        ports:
        - containerPort: 80